spring:
  main:
    banner-mode: "off"
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://[URL]
    username: [USERNAME]
    password: [PASSWORD]
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
  mvc:
    view:
      suffix: .jsp