spring:
    jpa:
        database: MYSQL
        hibernate:
          ddl-auto: validate
    datasource:
        url: jdbc:mysql://[URL]
        username: [USERNAME]
        password: [PASSWORD]
        driver-class-name: com.mysql.jdbc.Driver